apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: sv-event-comment-
  annotations:
    pipelinesascode.tekton.dev/on-comment: "^/pac-comment-sv-demo$"
spec:
  pipelineRef:
    resolver: cluster
    params:
      - name: kind
        value: pipeline
      - name: name
        value: pac-ref-type-pipeline
      - name: namespace
        value: demo-1
  params:
    - name: trigger-type
      value: "comment"
    - name: message
      value: "{{ trigger_comment }}"
    - name: source-repo
      value: "{{ repo_url }}"
    - name: source-branch
      value: "{{ source_branch }}"
    - name: target-branch
      value: "{{ target_branch }}"
    - name: revision
      value: "{{ revision }}"
    - name: pr-number
      value: "{{ pull_request_number }}"
  taskRunTemplate:
    serviceAccountName: default
    podTemplate:
      securityContext:
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
