apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: sv-ref-hub-python-
  annotations:
    pipelinesascode.tekton.dev/on-comment: "^/pac-python-hub$"
spec:
  pipelineRef:
    resolver: hub
    params:
      - name: catalog
        value: catalog
      - name: kind
        value: pipeline
      - name: name
        value: python-image-build-scan-deploy
      - name: version
        value: "0.1"
  params:
    - name: git-url
      value: "{{ repo_url }}"
    - name: git-revision
      value: "{{ revision }}"
    - name: images
      value:
        - "container-registry.catalog-test.svc.cluster.local:5000/sv-demo/python-hub:{{ revision }}"
    - name: tls-verify
      value: "false"
    - name: skip-trivy-scan
      value: "true"
  workspaces:
    - name: source
      emptyDir: {}
  taskRunTemplate:
    serviceAccountName: default
    podTemplate:
      securityContext:
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch