apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: sv-event-incoming-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[incoming]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
spec:
  pipelineRef:
    name: pac-ref-type-pipeline
  params:
    - name: trigger-type
      value: "incoming"
    - name: message
      value: "sv-demo incoming event"
    - name: source-repo
      value: "{{ repo_url }}"
    - name: source-branch
      value: "{{ source_branch }}"
    - name: target-branch
      value: "{{ target_branch }}"
    - name: revision
      value: "{{ revision }}"
    - name: pr-number
      value: ""
  taskRunTemplate:
    serviceAccountName: default
    podTemplate:
      securityContext:
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
