apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: sv-event-pr-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
spec:
  pipelineSpec:
    params:
      - name: trigger-type
        type: string
      - name: message
        type: string
      - name: source-repo
        type: string
      - name: source-branch
        type: string
      - name: target-branch
        type: string
      - name: revision
        type: string
      - name: pr-number
        type: string
    tasks:
      - name: show-ref-params
        params:
          - name: trigger-type
            value: "$(params.trigger-type)"
          - name: message
            value: "$(params.message)"
          - name: source-repo
            value: "$(params.source-repo)"
          - name: source-branch
            value: "$(params.source-branch)"
          - name: target-branch
            value: "$(params.target-branch)"
          - name: revision
            value: "$(params.revision)"
          - name: pr-number
            value: "$(params.pr-number)"
        taskSpec:
          params:
            - name: trigger-type
              type: string
            - name: message
              type: string
            - name: source-repo
              type: string
            - name: source-branch
              type: string
            - name: target-branch
              type: string
            - name: revision
              type: string
            - name: pr-number
              type: string
          steps:
            - name: echo
              image: registry.alauda.cn:60070/devops/tektoncd/hub/run-script:v3.21
              script: |
                #!/usr/bin/env sh
                set -eu
                echo "ref pipeline trigger-type=$(params.trigger-type)"
                echo "message=$(params.message)"
                echo "source-repo=$(params.source-repo)"
                echo "source-branch=$(params.source-branch)"
                echo "target-branch=$(params.target-branch)"
                echo "revision=$(params.revision)"
                echo "pr-number=$(params.pr-number)"
        timeout: 30m0s
      - name: run-script
        params:
          - name: script
            value: pwd
        taskRef:
          resolver: hub
          params:
            - name: kind
              value: task
            - name: catalog
              value: catalog
            - name: name
              value: run-script
            - name: version
              value: "0.1"
        timeout: 30m0s
  params:
    - name: trigger-type
      value: "pull_request"
    - name: message
      value: "sv-demo pull request event"
    - name: source-repo
      value: "{{ repo_url }}"
    - name: source-branch
      value: "{{ source_branch }}"
    - name: target-branch
      value: "{{ target_branch }}"
    - name: revision
      value: "{{ revision }}"
    - name: pr-number
      value: "{{ pull_request_number }}"
  taskRunTemplate:
    serviceAccountName: default
    podTemplate:
      securityContext:
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
