apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: hello-pac-run-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[master, main]"
spec:
  pipelineSpec:
    tasks:
      - name: hello
        taskSpec:
          steps:
            - name: echo
              image: registry.alauda.cn:60070/devops/tektoncd/hub/run-script:v3.21
              script: |
                echo "hello from pipelines as code."
