apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: hello-pac-run-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[master, main]"
spec:
  params:
    - name: trigger-type
      value: push
    - name: message
      value: "hello from pipelines as code"
  pipelineRef:
    name: hello-demo-pipeline
