apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: sv-cluster-resolver-main-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
spec:
  pipelineRef:
    resolver: cluster
    params:
      - name: kind
        value: pipeline
      - name: name
        value: pac-ref-type-pipeline
      - name: namespace
        value: demo-1
  params:
    - name: trigger-type
      value: "github-push-cluster-resolver-pipeline"
    - name: message
      value: "GitHub App push triggered cluster resolver pipelineRef run"
    - name: source-repo
      value: "{{ repo_url }}"
    - name: source-branch
      value: "{{ source_branch }}"
    - name: target-branch
      value: "{{ target_branch }}"
    - name: revision
      value: "{{ revision }}"
    - name: pr-number
      value: ""
  taskRunTemplate:
    serviceAccountName: default
    podTemplate:
      securityContext:
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
