apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: sv-event-tag-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[refs/tags/*]"
spec:
  pipelineRef:
    name: pac-ref-type-pipeline
  params:
    - name: trigger-type
      value: "tag"
    - name: message
      value: "sv-demo tag event: {{ git_tag }}"
    - name: source-repo
      value: "{{ repo_url }}"
    - name: source-branch
      value: "{{ source_branch }}"
    - name: target-branch
      value: "{{ target_branch }}"
    - name: revision
      value: "{{ revision }}"
    - name: pr-number
      value: ""
  taskRunTemplate:
    serviceAccountName: default
    podTemplate:
      securityContext:
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
